# Generated by Django 3.2.6 on 2021-11-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_section',
            field=models.ManyToManyField(blank=True, to='courses.CourseSection'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='episodes',
            field=models.ManyToManyField(blank=True, to='courses.Episode'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='related_course',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
    ]
